# Generated by Django 5.0.7 on 2024-08-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='international_titles',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='national_titles',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
